<?php

/**
 * Implements hook_mail().
 */
function nk_jsonapi_mail($key, &$message, $params) {
  
  //user_mail_tokens($variables, $data, $options);
  
  switch ($key) {
    case 'nk_jsonapi_mail':
    
      // Use the theme to send the message
      $theme_body = [
        '#theme' => 'nk_jsonapi_email',
        '#text' => $params['body'],
        '#sender_name' => $params['name'],
      ];
    
      // Set up the parameters for your email from the variables
      //$params['message'] = \Drupal::service('renderer')->render($theme_body);
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
    break;
  }

}

/**
 * Implements hook_theme().
 * To add the template definition.
 **/
function nk_jsonapi_theme($existing, $type, $theme, $path) {
  return [
    'nk_jsonapi_email' => [
      'variables' => [
        'text' => NULL,
        'sender_name' => NULL,
      ],
    ], 
  ];  
}